version: '2'
services:
  web:
    image: odoo:12.0
    volumes:
      - ./extra-addons:/mnt/extra-addons
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
